'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EET_service
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", ConfigurationName:="EET_service.EET")>  _
    Public Interface EET
        
        'CODEGEN: Probíhá generování kontraktu zprávy, protože název obálky (Trzba) zprávy OdeslaniTrzbyRequest neodpovídá výchozí hodnotě (OdeslaniTrzby)
        <System.ServiceModel.OperationContractAttribute(Action:="http://fs.mfcr.cz/eet/OdeslaniTrzby", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function OdeslaniTrzby(ByVal request As EET_service.OdeslaniTrzbyRequest) As EET_service.OdeslaniTrzbyResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class TrzbaHlavickaType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uuid_zpravyField As String
        
        Private dat_odeslField As Date
        
        Private prvni_zaslaniField As Boolean
        
        Private overeniField As Boolean
        
        Private overeniFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property uuid_zpravy() As String
            Get
                Return Me.uuid_zpravyField
            End Get
            Set
                Me.uuid_zpravyField = value
                Me.RaisePropertyChanged("uuid_zpravy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dat_odesl() As Date
            Get
                Return Me.dat_odeslField
            End Get
            Set
                Me.dat_odeslField = value
                Me.RaisePropertyChanged("dat_odesl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property prvni_zaslani() As Boolean
            Get
                Return Me.prvni_zaslaniField
            End Get
            Set
                Me.prvni_zaslaniField = value
                Me.RaisePropertyChanged("prvni_zaslani")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property overeni() As Boolean
            Get
                Return Me.overeniField
            End Get
            Set
                Me.overeniField = value
                Me.RaisePropertyChanged("overeni")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property overeniSpecified() As Boolean
            Get
                Return Me.overeniFieldSpecified
            End Get
            Set
                Me.overeniFieldSpecified = value
                Me.RaisePropertyChanged("overeniSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class OdpovedVarovaniType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kod_varovField As Integer
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property kod_varov() As Integer
            Get
                Return Me.kod_varovField
            End Get
            Set
                Me.kod_varovField = value
                Me.RaisePropertyChanged("kod_varov")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class OdpovedChybaType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private kodField As Integer
        
        Private testField As Boolean
        
        Private testFieldSpecified As Boolean
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property kod() As Integer
            Get
                Return Me.kodField
            End Get
            Set
                Me.kodField = value
                Me.RaisePropertyChanged("kod")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property test() As Boolean
            Get
                Return Me.testField
            End Get
            Set
                Me.testField = value
                Me.RaisePropertyChanged("test")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property testSpecified() As Boolean
            Get
                Return Me.testFieldSpecified
            End Get
            Set
                Me.testFieldSpecified = value
                Me.RaisePropertyChanged("testSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class OdpovedPotvrzeniType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fikField As String
        
        Private testField As Boolean
        
        Private testFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property fik() As String
            Get
                Return Me.fikField
            End Get
            Set
                Me.fikField = value
                Me.RaisePropertyChanged("fik")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property test() As Boolean
            Get
                Return Me.testField
            End Get
            Set
                Me.testField = value
                Me.RaisePropertyChanged("test")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property testSpecified() As Boolean
            Get
                Return Me.testFieldSpecified
            End Get
            Set
                Me.testFieldSpecified = value
                Me.RaisePropertyChanged("testSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class OdpovedHlavickaType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uuid_zpravyField As String
        
        Private bkpField As String
        
        Private dat_prijField As Date
        
        Private dat_prijFieldSpecified As Boolean
        
        Private dat_odmitField As Date
        
        Private dat_odmitFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property uuid_zpravy() As String
            Get
                Return Me.uuid_zpravyField
            End Get
            Set
                Me.uuid_zpravyField = value
                Me.RaisePropertyChanged("uuid_zpravy")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property bkp() As String
            Get
                Return Me.bkpField
            End Get
            Set
                Me.bkpField = value
                Me.RaisePropertyChanged("bkp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dat_prij() As Date
            Get
                Return Me.dat_prijField
            End Get
            Set
                Me.dat_prijField = value
                Me.RaisePropertyChanged("dat_prij")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dat_prijSpecified() As Boolean
            Get
                Return Me.dat_prijFieldSpecified
            End Get
            Set
                Me.dat_prijFieldSpecified = value
                Me.RaisePropertyChanged("dat_prijSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dat_odmit() As Date
            Get
                Return Me.dat_odmitField
            End Get
            Set
                Me.dat_odmitField = value
                Me.RaisePropertyChanged("dat_odmit")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dat_odmitSpecified() As Boolean
            Get
                Return Me.dat_odmitFieldSpecified
            End Get
            Set
                Me.dat_odmitFieldSpecified = value
                Me.RaisePropertyChanged("dat_odmitSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class BkpElementType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private digestField As BkpDigestType
        
        Private encodingField As BkpEncodingType
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property digest() As BkpDigestType
            Get
                Return Me.digestField
            End Get
            Set
                Me.digestField = value
                Me.RaisePropertyChanged("digest")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property encoding() As BkpEncodingType
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
                Me.RaisePropertyChanged("encoding")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Public Enum BkpDigestType
        
        '''<remarks/>
        SHA1
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Public Enum BkpEncodingType
        
        '''<remarks/>
        base16
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class PkpElementType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private digestField As PkpDigestType
        
        Private cipherField As PkpCipherType
        
        Private encodingField As PkpEncodingType
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property digest() As PkpDigestType
            Get
                Return Me.digestField
            End Get
            Set
                Me.digestField = value
                Me.RaisePropertyChanged("digest")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cipher() As PkpCipherType
            Get
                Return Me.cipherField
            End Get
            Set
                Me.cipherField = value
                Me.RaisePropertyChanged("cipher")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property encoding() As PkpEncodingType
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
                Me.RaisePropertyChanged("encoding")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
                Me.RaisePropertyChanged("Text")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Public Enum PkpDigestType
        
        '''<remarks/>
        SHA256
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Public Enum PkpCipherType
        
        '''<remarks/>
        RSA2048
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Public Enum PkpEncodingType
        
        '''<remarks/>
        base64
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class TrzbaKontrolniKodyType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pkpField As PkpElementType
        
        Private bkpField As BkpElementType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property pkp() As PkpElementType
            Get
                Return Me.pkpField
            End Get
            Set
                Me.pkpField = value
                Me.RaisePropertyChanged("pkp")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property bkp() As BkpElementType
            Get
                Return Me.bkpField
            End Get
            Set
                Me.bkpField = value
                Me.RaisePropertyChanged("bkp")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3")>  _
    Partial Public Class TrzbaDataType
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private dic_poplField As String
        
        Private dic_poverujicihoField As String
        
        Private id_provozField As Integer
        
        Private id_poklField As String
        
        Private porad_cisField As String
        
        Private dat_trzbyField As Date
        
        Private celk_trzbaField As Decimal
        
        Private zakl_nepodl_dphField As Decimal
        
        Private zakl_nepodl_dphFieldSpecified As Boolean
        
        Private zakl_dan1Field As Decimal
        
        Private zakl_dan1FieldSpecified As Boolean
        
        Private dan1Field As Decimal
        
        Private dan1FieldSpecified As Boolean
        
        Private zakl_dan2Field As Decimal
        
        Private zakl_dan2FieldSpecified As Boolean
        
        Private dan2Field As Decimal
        
        Private dan2FieldSpecified As Boolean
        
        Private zakl_dan3Field As Decimal
        
        Private zakl_dan3FieldSpecified As Boolean
        
        Private dan3Field As Decimal
        
        Private dan3FieldSpecified As Boolean
        
        Private cest_sluzField As Decimal
        
        Private cest_sluzFieldSpecified As Boolean
        
        Private pouzit_zboz1Field As Decimal
        
        Private pouzit_zboz1FieldSpecified As Boolean
        
        Private pouzit_zboz2Field As Decimal
        
        Private pouzit_zboz2FieldSpecified As Boolean
        
        Private pouzit_zboz3Field As Decimal
        
        Private pouzit_zboz3FieldSpecified As Boolean
        
        Private urceno_cerp_zuctField As Decimal
        
        Private urceno_cerp_zuctFieldSpecified As Boolean
        
        Private cerp_zuctField As Decimal
        
        Private cerp_zuctFieldSpecified As Boolean
        
        Private rezimField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dic_popl() As String
            Get
                Return Me.dic_poplField
            End Get
            Set
                Me.dic_poplField = value
                Me.RaisePropertyChanged("dic_popl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dic_poverujiciho() As String
            Get
                Return Me.dic_poverujicihoField
            End Get
            Set
                Me.dic_poverujicihoField = value
                Me.RaisePropertyChanged("dic_poverujiciho")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property id_provoz() As Integer
            Get
                Return Me.id_provozField
            End Get
            Set
                Me.id_provozField = value
                Me.RaisePropertyChanged("id_provoz")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property id_pokl() As String
            Get
                Return Me.id_poklField
            End Get
            Set
                Me.id_poklField = value
                Me.RaisePropertyChanged("id_pokl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property porad_cis() As String
            Get
                Return Me.porad_cisField
            End Get
            Set
                Me.porad_cisField = value
                Me.RaisePropertyChanged("porad_cis")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dat_trzby() As Date
            Get
                Return Me.dat_trzbyField
            End Get
            Set
                Me.dat_trzbyField = value
                Me.RaisePropertyChanged("dat_trzby")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property celk_trzba() As Decimal
            Get
                Return Me.celk_trzbaField
            End Get
            Set
                Me.celk_trzbaField = value
                Me.RaisePropertyChanged("celk_trzba")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property zakl_nepodl_dph() As Decimal
            Get
                Return Me.zakl_nepodl_dphField
            End Get
            Set
                Me.zakl_nepodl_dphField = value
                Me.RaisePropertyChanged("zakl_nepodl_dph")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zakl_nepodl_dphSpecified() As Boolean
            Get
                Return Me.zakl_nepodl_dphFieldSpecified
            End Get
            Set
                Me.zakl_nepodl_dphFieldSpecified = value
                Me.RaisePropertyChanged("zakl_nepodl_dphSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property zakl_dan1() As Decimal
            Get
                Return Me.zakl_dan1Field
            End Get
            Set
                Me.zakl_dan1Field = value
                Me.RaisePropertyChanged("zakl_dan1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zakl_dan1Specified() As Boolean
            Get
                Return Me.zakl_dan1FieldSpecified
            End Get
            Set
                Me.zakl_dan1FieldSpecified = value
                Me.RaisePropertyChanged("zakl_dan1Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dan1() As Decimal
            Get
                Return Me.dan1Field
            End Get
            Set
                Me.dan1Field = value
                Me.RaisePropertyChanged("dan1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dan1Specified() As Boolean
            Get
                Return Me.dan1FieldSpecified
            End Get
            Set
                Me.dan1FieldSpecified = value
                Me.RaisePropertyChanged("dan1Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property zakl_dan2() As Decimal
            Get
                Return Me.zakl_dan2Field
            End Get
            Set
                Me.zakl_dan2Field = value
                Me.RaisePropertyChanged("zakl_dan2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zakl_dan2Specified() As Boolean
            Get
                Return Me.zakl_dan2FieldSpecified
            End Get
            Set
                Me.zakl_dan2FieldSpecified = value
                Me.RaisePropertyChanged("zakl_dan2Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dan2() As Decimal
            Get
                Return Me.dan2Field
            End Get
            Set
                Me.dan2Field = value
                Me.RaisePropertyChanged("dan2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dan2Specified() As Boolean
            Get
                Return Me.dan2FieldSpecified
            End Get
            Set
                Me.dan2FieldSpecified = value
                Me.RaisePropertyChanged("dan2Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property zakl_dan3() As Decimal
            Get
                Return Me.zakl_dan3Field
            End Get
            Set
                Me.zakl_dan3Field = value
                Me.RaisePropertyChanged("zakl_dan3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property zakl_dan3Specified() As Boolean
            Get
                Return Me.zakl_dan3FieldSpecified
            End Get
            Set
                Me.zakl_dan3FieldSpecified = value
                Me.RaisePropertyChanged("zakl_dan3Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property dan3() As Decimal
            Get
                Return Me.dan3Field
            End Get
            Set
                Me.dan3Field = value
                Me.RaisePropertyChanged("dan3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property dan3Specified() As Boolean
            Get
                Return Me.dan3FieldSpecified
            End Get
            Set
                Me.dan3FieldSpecified = value
                Me.RaisePropertyChanged("dan3Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cest_sluz() As Decimal
            Get
                Return Me.cest_sluzField
            End Get
            Set
                Me.cest_sluzField = value
                Me.RaisePropertyChanged("cest_sluz")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cest_sluzSpecified() As Boolean
            Get
                Return Me.cest_sluzFieldSpecified
            End Get
            Set
                Me.cest_sluzFieldSpecified = value
                Me.RaisePropertyChanged("cest_sluzSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pouzit_zboz1() As Decimal
            Get
                Return Me.pouzit_zboz1Field
            End Get
            Set
                Me.pouzit_zboz1Field = value
                Me.RaisePropertyChanged("pouzit_zboz1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pouzit_zboz1Specified() As Boolean
            Get
                Return Me.pouzit_zboz1FieldSpecified
            End Get
            Set
                Me.pouzit_zboz1FieldSpecified = value
                Me.RaisePropertyChanged("pouzit_zboz1Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pouzit_zboz2() As Decimal
            Get
                Return Me.pouzit_zboz2Field
            End Get
            Set
                Me.pouzit_zboz2Field = value
                Me.RaisePropertyChanged("pouzit_zboz2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pouzit_zboz2Specified() As Boolean
            Get
                Return Me.pouzit_zboz2FieldSpecified
            End Get
            Set
                Me.pouzit_zboz2FieldSpecified = value
                Me.RaisePropertyChanged("pouzit_zboz2Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property pouzit_zboz3() As Decimal
            Get
                Return Me.pouzit_zboz3Field
            End Get
            Set
                Me.pouzit_zboz3Field = value
                Me.RaisePropertyChanged("pouzit_zboz3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property pouzit_zboz3Specified() As Boolean
            Get
                Return Me.pouzit_zboz3FieldSpecified
            End Get
            Set
                Me.pouzit_zboz3FieldSpecified = value
                Me.RaisePropertyChanged("pouzit_zboz3Specified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property urceno_cerp_zuct() As Decimal
            Get
                Return Me.urceno_cerp_zuctField
            End Get
            Set
                Me.urceno_cerp_zuctField = value
                Me.RaisePropertyChanged("urceno_cerp_zuct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property urceno_cerp_zuctSpecified() As Boolean
            Get
                Return Me.urceno_cerp_zuctFieldSpecified
            End Get
            Set
                Me.urceno_cerp_zuctFieldSpecified = value
                Me.RaisePropertyChanged("urceno_cerp_zuctSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property cerp_zuct() As Decimal
            Get
                Return Me.cerp_zuctField
            End Get
            Set
                Me.cerp_zuctField = value
                Me.RaisePropertyChanged("cerp_zuct")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property cerp_zuctSpecified() As Boolean
            Get
                Return Me.cerp_zuctFieldSpecified
            End Get
            Set
                Me.cerp_zuctFieldSpecified = value
                Me.RaisePropertyChanged("cerp_zuctSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property rezim() As Integer
            Get
                Return Me.rezimField
            End Get
            Set
                Me.rezimField = value
                Me.RaisePropertyChanged("rezim")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Trzba", WrapperNamespace:="http://fs.mfcr.cz/eet/schema/v3", IsWrapped:=true)>  _
    Partial Public Class OdeslaniTrzbyRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=0)>  _
        Public Hlavicka As EET_service.TrzbaHlavickaType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=1)>  _
        Public Data As EET_service.TrzbaDataType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=2)>  _
        Public KontrolniKody As EET_service.TrzbaKontrolniKodyType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Hlavicka As EET_service.TrzbaHlavickaType, ByVal Data As EET_service.TrzbaDataType, ByVal KontrolniKody As EET_service.TrzbaKontrolniKodyType)
            MyBase.New
            Me.Hlavicka = Hlavicka
            Me.Data = Data
            Me.KontrolniKody = KontrolniKody
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="Odpoved", WrapperNamespace:="http://fs.mfcr.cz/eet/schema/v3", IsWrapped:=true)>  _
    Partial Public Class OdeslaniTrzbyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=0)>  _
        Public Hlavicka As EET_service.OdpovedHlavickaType
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute("Chyba", GetType(OdpovedChybaType)),  _
         System.Xml.Serialization.XmlElementAttribute("Potvrzeni", GetType(OdpovedPotvrzeniType))>  _
        Public Item As Object
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://fs.mfcr.cz/eet/schema/v3", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute("Varovani")>  _
        Public Varovani() As EET_service.OdpovedVarovaniType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Hlavicka As EET_service.OdpovedHlavickaType, ByVal Item As Object, ByVal Varovani() As EET_service.OdpovedVarovaniType)
            MyBase.New
            Me.Hlavicka = Hlavicka
            Me.Item = Item
            Me.Varovani = Varovani
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface EETChannel
        Inherits EET_service.EET, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EETClient
        Inherits System.ServiceModel.ClientBase(Of EET_service.EET)
        Implements EET_service.EET
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EET_service_EET_OdeslaniTrzby(ByVal request As EET_service.OdeslaniTrzbyRequest) As EET_service.OdeslaniTrzbyResponse Implements EET_service.EET.OdeslaniTrzby
            Return MyBase.Channel.OdeslaniTrzby(request)
        End Function
        
        Public Function OdeslaniTrzby(ByVal Hlavicka As EET_service.TrzbaHlavickaType, ByVal Data As EET_service.TrzbaDataType, ByVal KontrolniKody As EET_service.TrzbaKontrolniKodyType, <System.Runtime.InteropServices.OutAttribute()> ByRef Item As Object, <System.Runtime.InteropServices.OutAttribute()> ByRef Varovani() As EET_service.OdpovedVarovaniType) As EET_service.OdpovedHlavickaType
            Dim inValue As EET_service.OdeslaniTrzbyRequest = New EET_service.OdeslaniTrzbyRequest()
            inValue.Hlavicka = Hlavicka
            inValue.Data = Data
            inValue.KontrolniKody = KontrolniKody
            Dim retVal As EET_service.OdeslaniTrzbyResponse = CType(Me,EET_service.EET).OdeslaniTrzby(inValue)
            Item = retVal.Item
            Varovani = retVal.Varovani
            Return retVal.Hlavicka
        End Function
    End Class
End Namespace
