'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    'pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    'Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    's parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    '''<summary>
    '''  Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SWAPP_Builder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '''  vyhledání prostředků pomocí třídy prostředků se silnými typy.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_to_favorite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_to_favorite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property app_builder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("app_builder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attachment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property db_commit_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_commit_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property db_commit_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_commit_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property default_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("default_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filtered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filtered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property key_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property not_filtered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("not_filtered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        '''</summary>
        Friend ReadOnly Property preview_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("preview_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        '''</summary>
        Friend ReadOnly Property report() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("report", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property show() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("show", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sql() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sql", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        '''</summary>
        Friend ReadOnly Property terminal() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("terminal", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property waiting1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("waiting1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property waiting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("waiting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property waiting3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("waiting3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property waiting4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("waiting4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property waiting5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("waiting5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
